### ISSUE TITLE
Setting default video scrapers by folder/action?

### ISSUE THREAD

**Issue by adultsesamestreet** [adultmm/AdultMediaManager#43]
When I'm scraping a folder full of videos from a specific site, (e.g. allanal.com) its a bit annoying that I have to manually denote the scraper each and every time that I need to scrape a new video for the site. 

Would it be possible to have the folder that its pointed to have a default scraper for it, that can be set for the user?
For example, if I add a folder called, ...\AllAnal.com\ 
could I then have another interaction menu to indicate to scrape any content in this folder using the AllAnal.com scraper?

If not, could it be modified that instead of using just the Data18.com, that we could manually set which scraper to use for the default scrape? See Example picture below for what I mean. 

Thank you in advance, just thought this might be a helpful feature :)

![example](https://user-images.githubusercontent.com/105399921/167970151-74c92e8f-858a-4c34-862a-6b5a05fba268.png)

**Comment by adultmm** [comment]
Hi @adultsesamestreet,

AdultMediaScraper tries to match the used scaper(s) by the full path, so if AllAnal.com appears anywhere in the path, it should work.

\AllAnal.com\
\AllAnal.com siterip\
Any Folder\[AllAnal.com] Scene Title.mkv
...

If it doesn't work, I think, it's a bug. Please, send me the full path of some erroneous files, and I'll check it.

Cheers

**Comment by adultsesamestreet** [comment]
Hey,

Hmm. Yeah, I can't seem to get videos to autodetect. An example file path is below:

H:\21EroticAnal.com\ALadysFlower_s01_KristofCale_LiluMoon_720p.mp4

I've also tried renaming the folder Www.21Naturals.com to match the scraper name, but to no avail. Any suggestions?

**Comment by adultmm** [comment]
Hi @adultsesamestreet,

I've tested the above path, and - I think - my plugin correctly detects the "21Naturals" scraper. You can see it in the attached screenshot (circled in red). If you press Ctrl+C on the movie, you should see the same. Am I right?

So the scraper is detected, but my plugin won't automatically scrape the movie, because the score of the title matching is very low, only 73 out of 100. ("ALadysFlower_s01_KristofCale_LiluMoo" vs. "A Lady's Flower". 

I hope, it'll help you. 

![issue-43](https://user-images.githubusercontent.com/82322590/169366499-f17c5c7f-8bca-4e33-8786-076b50182045.png)

**Comment by adultmm** [comment]
No response, so I'm closing it.
