### ISSUE TITLE
File Naming?

### ISSUE THREAD

**Issue by OriginalFlavor** [adultmm/AdultMediaManager#6]
Is there a preferred file naming scheme?
Does it depend by site?

**Comment by adultmm** [comment]
Hi OriginalFlavor,

EMM creates the title from the filename, I don't know the exact algorithm, but it removes resolution and other quality markers. 
In "auto mode" AdultScraper tries different versions of the given title (removes bracketed content, removes dates, removes XXX, converts roman numbers, etc) while finds something. It uses the search function of the sites if any or a search engine otherwise, so the results may be very different. 

If you have an example that doesn't work but you think it should, please send it to me and I'll try to improve the algorithm.

Is this information is enough for you?
