### ISSUE TITLE
Unable to open the setting option after setting Chinese

### ISSUE THREAD

**Issue by y2kcan** [adultmm/AdultMediaManager#62]
![image](https://user-images.githubusercontent.com/103928359/194430123-5600416a-b80f-44c8-abf9-cae32e27f051.png)

**Comment by adultmm** [comment]
The problem is in Ember Media Manager, not in my plugin. 
Please, report the error to Dan: https://forum.kodi.tv/forumdisplay.php?fid=195

System.Text.StringBuilder.FormatError()
System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
generic.EmberCore.BulkRename.frmSettingsHolder.SetUp()
